name: general-exploration-landcover
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pystac-client
  - odc-stac
  - jupyter
  - geopandas
  - rioxarray
  - seaborn
  - xarray-spatial
